### ISSUE TITLE
Inventory Design Proposal

### ISSUE THREAD

**Issue by goshlanguage** [goshlanguage/cerulean#14]
Decoupling the inventory storage into a data store should help us avoid circular dependencies. 

Here's a [crude diagram](https://docs.google.com/drawings/d/1aknJTo_Ry09L3aS39XlOXv9-2-E-_9XgdIqPUsNjLbQ/edit?usp=sharing), but essentially if we use a data store that we can pass across functional (and library) boundaries, I believe it will simplify test assertions and give us a simple design. 

We achieve this by having a top level scoped data object we can reference and make assertions from, without having to construct additional clients, and their respective API calls to get things like subscriptions, then resource groups for example. You would need to do this fairly often. 

To oppose this approach, we could write helper functions for common tasks like fetching and parsing subs and resource groups. 

Further, having each service contain it's own inventory could also be the correct approach. At large companies, organizations keep their own databases that are relevant to their own services. It likely makes sense to replicate this.

To this end, services commonly query other team's APIs for relevant information, and those calls must be made sequentially to obtain necessary information.

**Comment by jessemillar** [comment]
I think this is great. Love that the implementation in the PR (linked above) doesn't spin up an external database. Keeps things nice and simple. Namespacing the key/value pairs with service name as we discussed in our "standup" meeting today seems logical and simple enough to not cause issues/conflicts in the near future. We'll have to figure out a namespacing scheme/rule that incorporates the name of the service *and* the API version (unless we're handling API versioning completely at the unmarshaling level).
